### ISSUE TITLE
Create MPI Sub-communicator

### ISSUE THREAD

**Issue by qing42102** [cwsmith/omegahPetsc#1]
Create two communicators in ex12 each with half of the processes by using `MPI_Comm_Split`. Each instance should be solving the same problem on the same mesh.

**Comment by qing42102** [comment]
@cwsmith I implemented the sub-communicator and want to confirm with you whether the results are correct. 
Here's the rank and size of `MPI_COMM_WORLD` before the split. This is with 4 processes split into 2 sub-communicators. 
```
Rank: 0, Size: 4
Rank: 2, Size: 4
Rank: 1, Size: 4
Rank: 3, Size: 4
```
This is the rank and size of the new communicator after the split. 
```
Split Rank: 1, Split Size: 2
Split Rank: 0, Split Size: 2
Split Rank: 0, Split Size: 2
Split Rank: 1, Split Size: 2
```
This is the partitioning of the mesh for each rank in the 2 instances of PETSc. 
```
0 numCells: 11876 numVertices: 6088
1 numCells: 11878 numVertices: 6096
1 numCells: 11878 numVertices: 6096
0 numCells: 11876 numVertices: 6088
```

**Comment by cwsmith** [comment]
This looks good! :+1:

**Comment by qing42102** [comment]
[Final commit](https://github.com/cwsmith/omegahPetsc/commit/79f719184fe96ff36a15101c5dbe638baee6dde0) for this
