### ISSUE TITLE
Running tri_bddc test with xgc mesh

### ISSUE THREAD

**Issue by qing42102** [cwsmith/omegahPetsc#3]
The tri_bddc test is by using the following command line with 5 processes:
```
-run_type full -petscpartitioner_type simple -dm_refine 0 -bc_type dirichlet -interpolate 1 -petscspace_degree 1 -ksp_type gmres -ksp_gmres_restart 100 -ksp_rtol 1.0e-9 -dm_mat_type is -pc_type bddc -snes_monitor_short -ksp_monitor_short -snes_converged_reason ::ascii_info_detail -ksp_converged_reason -snes_view -show_solution 0
```
The output will state the solver did not converge. 
```
Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
                 PC_FAILED due to FACTOR_NOERROR 
```

What is interesting is that running this test with 1 and 2 processes allows the solver to converge.

**Comment by cwsmith** [comment]
Does the solution from the 1 process case look reasonable (using the visualization approaches we previously used)?  What version/commit of `omegahPetsc` produces the error?

**Comment by qing42102** [comment]
@cwsmith The commit link is [here](https://github.com/cwsmith/omegahPetsc/commit/9f74af411f005b0219abe01bcc6f6a5e60eaf8a6#diff-76cf628441d3a09632fe6d9de960b2d7). Please note that the sub-communicator has not been added in and `mesh.balance()` is not used. So PETSc is doing the partitioning. 

The solution looks correct using 1 process. Using 2 processes, the mesh and the solution look kind of different. Is that because of the partitioning?

**Comment by cwsmith** [comment]
@qing42102 Would you please post screenshots of the solution?  I'd like to take a look at the differences between 1 and 2 processes.

**Comment by qing42102** [comment]
@cwsmith 
This is 1 process with `-vec_view`. 
![image](https://user-images.githubusercontent.com/55563930/85599628-ae6ceb00-b61a-11ea-86fd-a49f2dbf8ad3.png)
This is 2 processes. 
![Annotation 2020-06-24 125621](https://user-images.githubusercontent.com/55563930/85599771-d65c4e80-b61a-11ea-95bd-4774a3fa0091.png)
This is 3 processes. 
![Annotation 2020-06-24 125829](https://user-images.githubusercontent.com/55563930/85599782-d8261200-b61a-11ea-8d94-88b29e96bec7.png)

**Comment by qing42102** [comment]
This output is for 1 process.
[test_1proc.log](https://github.com/cwsmith/omegahPetsc/files/4837556/test_1proc.log)
This output is for 2 processes. 
[test_2proc.log](https://github.com/cwsmith/omegahPetsc/files/4837557/test_2proc.log)

**Comment by cwsmith** [comment]
The dof distribution in `test_2proc.log` looks good.  I'd suggest running the simple triangular mesh of the square plate (probably the petsc mesh instead of the omega_h version of the mesh) and check if the convergence and visualization has similar characteristics (slow and odd).

**Comment by qing42102** [comment]
The issue with the visualization seems to be because of VNC viewer. This can be fixed by viewing the solution in ParaView. 

Adding `-vec_view vtk:name.vtu:vtk_vtu` to the command line argument will generate a vtk file named `name.vtk`, which can be viewed in ParaView. The solution remains the same when changing the number of processes. 
![screenshot](https://user-images.githubusercontent.com/55563930/87854537-abdf7780-c8e0-11ea-83c2-082e4e65671d.png)


The only issue is when running multiple instances with a sub-communicator. PETSc seems to be incapable of producing one vtk file for each instance.
