### ISSUE TITLE
Change to use DMPlexCreateFromCellListParallel

### ISSUE THREAD

**Issue by qing42102** [cwsmith/omegahPetsc#4]
The previous use of `DMPlexCreateFromCellList` was incorrect and creates independent meshes and matrices on each process. `DMPlexCreateFromCellListParallel` should be the correct function. 

The following PETSc example demonstrates the use of `DMPlexCreateFromCellListParallel`
https://gitlab.com/petsc/petsc/-/blob/master/src/dm/impls/plex/tests/ex18.c

The following list needs to be checked to ensure the mesh is working as intended:
1. Run with box and XGC mesh
2. Run a test with 1 and multiple processes
3. The Omega_h vtk file after partitioning
4. The PETSc solution vtk file
5. The min and max element to indicate whether it is global element id
6. Whether the matrix distribution matches the mesh partition
7. The sub-communicator

**Comment by qing42102** [comment]
For `DMPlexCreateFromCellListParallel`, `numVertices` is the number of vertices owned by this process. The sum of number of vertices across all processes should be the total number of vertices the full mesh has. 
The `cell` contains vertices to element adjacency, but the vertex ids are global. 
The `vertexCoords` contains the coordinates for the vertices owned by this process. There should not be an overlap between this array across all processes. 

@cwsmith Do you know of a way to get a global array of vertex coordinates in Omega_h? With the Omega_h partitioning, the current coordinates arrays have overlap between them.

**Comment by cwsmith** [comment]
The info you need is the ownership of each entity on the part boundary.  Take a look at Figure 10 and the description of it on page A:13 in this paper:
https://www.scorec.rpi.edu/REPORTS/2014-9.pdf

The omega_h api to check ownership is:
https://github.com/SNLComputation/omega_h/blob/75f48cf629854862b5951de2e811745cbdcb3a72/src/Omega_h_mesh.hpp#L139
It returns the array of entities (of the specified dimension) owned by the current process.

**Comment by qing42102** [comment]
@cwsmith For some reason, `owned` produces a bunch of garbage values. I instead used `ask_owners`. 

For the input to `DMPlexCreateFromCellListParallel`, I just realized that the vertices id has to be sequential across ranks. So if a mesh has 9 vertices in total with 3 vertices distributed to 3 ranks, then rank 0 must contain vertices with global id 0-2 and rank 1 must contain vertices 3-5. and rank 3 must contain vertices 6-8. I think this is how PETSc match the coordinates to the vertex global id. The number of vertices distributed to each rank probably doesn't matter as long as the coordinates match. Can the ownership of entities still help in this case with the coordinates?

**Comment by cwsmith** [comment]
Is the sequential requirement documented somewhere?  It sounds a bit odd.

**Comment by qing42102** [comment]
@cwsmith I kind of inferred it from the ex18.c in the top post, so it may not be correct. If you look at line 41-105, the pictures and description shows what I said. Looking at the corresponding code for those tests [here](https://gitlab.com/petsc/petsc/-/blob/master/src/dm/impls/plex/tests/ex18.c#L405-524), you can see that the coordinates inputted into each rank matches the sequential global vertex id of vertex. 
I also don't know how else can PETSc match the input vertex coordinates array to the correct vertex.

**Comment by cwsmith** [comment]
The LibCEED project uses DMPlex; we may find some useful code snippets there.

https://github.com/CEED/libCEED

**Comment by cwsmith** [comment]
Following what is done in DMPlexCreateFromCellListParallelPetsc

I think we need to first call:

DMPlexBuildFromCellListParallel

https://gitlab.com/petsc/petsc/-/blob/caa22a8a6959549f3567c51cb8028520e3252e52/src/dm/impls/plex/plexcreate.c#L2775-2826

which returns a PetscSF that I *think* tells us which process owns which vertices.  From there we can fill in the vertex coordinate arrays and call:

DMPlexBuildCoordinatesFromCellListParallel

https://gitlab.com/petsc/petsc/-/blob/caa22a8a6959549f3567c51cb8028520e3252e52/src/dm/impls/plex/plexcreate.c#L2930-2947

**Comment by qing42102** [comment]
@cwsmith After pulling the newest version of PETSc and reinstalling it with the previous instruction, I cannot compile `ex12.cpp`. 
This is the error I get
```
In file included from /gpfs/u/barn/MPFS/MPFSzhqg/petsc/include/petscsection.h:3:0,
                 from /gpfs/u/barn/MPFS/MPFSzhqg/petsc/include/petscdmplex.h:7,
                 from /gpfs/u/home/MPFS/MPFSzhqg/barn/omegahPetsc/ex12.cpp:17:
/gpfs/u/barn/MPFS/MPFSzhqg/petsc/include/petscsys.h:14:10: fatal error: petscconf.h: No such file or directory
 #include <petscconf.h>
``` 
Do you know if the instructions changed when reinstalling the newer version?

**Comment by qing42102** [comment]
@cwsmith 
1. I was able to generate a PetscSF and view it with ` PetscSFView`, but I am still trying to understand how it tells me the vertex ownership. Currently, it only gives me the local vertex id. For reference, this is a [paper/tutorial](https://lists.mcs.anl.gov/pipermail/petsc-dev/attachments/20111224/7bfa1e70/attachment.pdf) written by Jed Brown on PETSc star forest. 

2. If we are using `DMPlexBuildFromCellListParallel` and `DMPlexBuildCoordinatesFromCellListParallel`, wouldn't we end up with the same problem, since `DMPlexCreateFromCellListParallelPetsc` uses both of these functions? The PetscSF object we get from `BuildFromCellListParallel` is same as the one generated by `CreateFromCellListParallelPetsc`. Unless we are changing the PetscSF object, wouldn't we need to input the same vertex coordinates array into `BuildCoordinatesFromCellListParallel` as `CreateFromCellListParallelPetsc`?

**Comment by cwsmith** [comment]
Hmmm.   Let's take a look in the morning.  One sanity check for these first tests; be sure PETSC is using MPI_COMM_WORLD with no subcommunicators.

**Comment by cwsmith** [comment]
The star forest produced by `DMPlexBuildFromCellListParallel()` for mesh vertices makes sense for a simple 8 triangle mesh of a square.  The attached chicken scratch depicts the vertex graph created for it given that vertices 0-5 are owned by rank 0 and 6-8 by rank 1.  

![foo](https://user-images.githubusercontent.com/1024438/89673618-a90aed80-d8b4-11ea-85eb-3e6637601f14.png)

Note, the global ids of the vertices owned by rank 0 and 1 are sequential (no numbers skipped) in the above example and thus the root nodes in the star forest are listed in order of global vertex ids across the two ranks.   We are not sure how the root nodes in the star forest map to our meshes vertex global ids if the global ids of owned vertices on a given process are non-sequential.

**Comment by qing42102** [comment]
Using a new set of vertices to elements adjacencies, rank 0 should contain vertices 0-4 and 8 while rank 1 should contain 5-7. 
This is the output for PETSc SF. 
```
  [0] Number of roots=6, leaves=6, remote ranks=2
  [0] 0 <- (0,0)
  [0] 1 <- (0,1)
  [0] 2 <- (0,2)
  [0] 3 <- (0,3)
  [0] 4 <- (0,4)
  [0] 5 <- (1,2)
  [1] Number of roots=3, leaves=6, remote ranks=2
  [1] 0 <- (0,0)
  [1] 1 <- (0,4)
  [1] 2 <- (0,5)
  [1] 3 <- (1,0)
  [1] 4 <- (1,1)
  [1] 5 <- (1,2)
```

It seems that rank 0 still owns vertices 0-5 and rank 1 owns 6-8. 
![vertex](https://user-images.githubusercontent.com/55563930/89809689-ef0cbf00-db09-11ea-8d5e-d65a12c3311c.png)

**Comment by cwsmith** [comment]
@qing42102 Would you please push the code for this test to a branch?

**Comment by qing42102** [comment]
@cwsmith Here's the branch. https://github.com/cwsmith/omegahPetsc/tree/parallel_box_test

**Comment by cwsmith** [comment]
OK.  I see two ways forward:

1. figure out how to broadcast 'missing' coordinates via the star forest (SF) to the processes that need them
2. create a SF from the part boundary vertices to stitch together independent dmplex objects on each process

The guidance from the petsc folks has been that the `DMPlexCreateFromCellListParallelPetsc` is less efficient than (2) and if we add in the communication from step (1) it would be another increment slower. Given this, I think we should work on (2).  

@qing42102 This example looks helpful:
https://www.mcs.anl.gov/petsc/petsc-current/src/vec/is/sf/tutorials/ex1.c.html
lines 142-165 create arrays representing the simple graph and 169-172 pass those arrays into the creation APIs.  I'll start putting together an email to the petsc mailing list to ask about the APIs to combine the SF and the dmplex objects.

**Comment by cwsmith** [comment]
@qing42102 Compiling the `parallel_box_test` branch on aimos produces the following errors on aimos.  Are there changes that were not pushed?  Note, I'm using petsc master (`753428f`).

```
MPFSsmth@dcsfen02: ~/barn/build-omegahPetsc-aimosGcc740Spectrum $ make
Scanning dependencies of target ex12
[ 50%] Building CUDA object CMakeFiles/ex12.dir/ex12.cpp.o
/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(649): error: argument of type "PetscBool" is incompatible with parameter of type "PetscSF *"

/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(649): error: too many arguments in function call

/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(743): warning: variable "part" was declared but never referenced

/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(745): warning: variable "distributedMesh" was declared but never referenced

/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(1043): warning: variable "hasLevel" was set but never used

/gpfs/u/home/MPFS/MPFSsmth/barn/omegahPetsc/ex12.cpp(1122): warning: variable "hasLevel" was set but never used

2 errors detected in the compilation of "/tmp/tmpxft_00005e31_00000000-6_ex12.cpp1.ii".
make[2]: *** [CMakeFiles/ex12.dir/ex12.cpp.o] Error 1
make[1]: *** [CMakeFiles/ex12.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by qing42102** [comment]
@cwsmith I am using the `caa22a8a` branch. It seems that the `DMPlexBuildFromCellListParallel` function changed since then. I will update PETSc and then ex12.cpp.

**Comment by cwsmith** [comment]
@qing42102 Thank you.  `ex12` from `parallel_box_test` builds now.  What is the run command (I recall there being many arguments)?

**Comment by qing42102** [comment]
@cwsmith This is the current command I use 
```
-run_type full -petscpartitioner_type parmetis -dm_refine 0 -bc_type dirichlet -interpolate 1 -petscspace_degree 1 -ksp_type gmres -ksp_gmres_restart 100 -ksp_rtol 1.0e-9 -dm_mat_type is -pc_type bddc -snes_monitor_short -ksp_monitor_short -snes_converged_reason ::ascii_info_detail -ksp_converged_reason -snes_view -show_solution 0 -mesh box -log_view
```
Some of the commands, like `-petscpartitioner_type`, is currently not used, but I just keep it there.

**Comment by cwsmith** [comment]
@qing42102 Thank you; that worked.

I modified ex12 for cuda-less execution https://github.com/cwsmith/omegahPetsc/commit/1d339dfd3ffb8b3c90fc699a1e91883a6bf66696; there was some mixing of gpu and cpu array syntax that was concerning.

In petsc I added a few print statements and a call to print the `point SF`:

``` diff
MPFSsmth@dcsfen02: /gpfs/u/barn/MPFS/MPFSsmth/petsc (master)$ git diff
diff --git a/src/dm/impls/plex/plexcreate.c b/src/dm/impls/plex/plexcreate.c
index 8282098..a3f8a2d8 100644
--- a/src/dm/impls/plex/plexcreate.c
+++ b/src/dm/impls/plex/plexcreate.c
@@ -2874,6 +2874,7 @@ PetscErrorCode DMPlexBuildFromCellListParallel(DM dm, PetscInt numCells, PetscIn
   ierr = PetscFree(verticesAdj);CHKERRQ(ierr);
   /* Build pointSF */
   ierr = PetscMalloc2(numVerticesAdj, &vertexLocal, numVertices, &vertexOwner);CHKERRQ(ierr);
+  fprintf(stderr, "%d 0.1 numVerticesAdj numVertices %d %d\n", rank, numVerticesAdj, numVertices);
   for (v = 0; v < numVerticesAdj; ++v) {vertexLocal[v].index = v+numCells; vertexLocal[v].rank = rank;}
   for (v = 0; v < numVertices;    ++v) {vertexOwner[v].index = -1;         vertexOwner[v].rank = -1;}
   ierr = PetscSFReduceBegin(sfVert, MPIU_2INT, vertexLocal, vertexOwner, MPI_MAXLOC);CHKERRQ(ierr);
@@ -2896,7 +2897,9 @@ PetscErrorCode DMPlexBuildFromCellListParallel(DM dm, PetscInt numCells, PetscIn
   if (g != numVerticesGhost) SETERRQ2(PETSC_COMM_SELF, PETSC_ERR_PLIB, "Invalid number of vertex ghosts %D should be %D", g, numVerticesGhost);
   ierr = DMGetPointSF(dm, &sfPoint);CHKERRQ(ierr);
   ierr = PetscObjectSetName((PetscObject) sfPoint, "point SF");CHKERRQ(ierr);
+  fprintf(stderr, "%d 0.2 numcells numVerticesAdj numVerticesGhost %d %d %d\n", rank, numCells, numVerticesAdj, numVerticesGhost);
   ierr = PetscSFSetGraph(sfPoint, numCells+numVerticesAdj, numVerticesGhost, localVertex, PETSC_OWN_POINTER, remoteVertex, PETSC_OWN_POINTER);CHKERRQ(ierr);
+  PetscSFView(sfPoint, PETSC_VIEWER_STDOUT_WORLD);
   ierr = PetscLayoutDestroy(&vLayout);CHKERRQ(ierr);
   /* Fill in the rest of the topology structure */
   ierr = DMPlexSymmetrize(dm);CHKERRQ(ierr);
```

Running with these changes produces the following output for `Vertex SF` and `point SF`:

```
PetscSF Object: Vertex Ownership SF 2 MPI processes
  type: basic
    sort=rank-order
  [0] Number of roots=6, leaves=6, remote ranks=1
  [0] 0 <- (0,0)
  [0] 1 <- (0,1)
  [0] 2 <- (0,2)
  [0] 3 <- (0,3)
  [0] 4 <- (0,4)
  [0] 5 <- (0,5)
  [1] Number of roots=3, leaves=6, remote ranks=2
  [1] 0 <- (0,0)
  [1] 1 <- (0,3)
  [1] 2 <- (0,5)
  [1] 3 <- (1,0)
  [1] 4 <- (1,1)
  [1] 5 <- (1,2)
```

At first glance, it looks like the point SF has roots on each node for each vertex and element.  The leaves appear to exist for  owned boundary vertices and point at the non-owners.  Is that your understanding?  Either way, I think we should ask about the specific definition.

```
PetscSF Object: `point SF` 2 MPI processes
  type: basic
    sort=rank-order
  [0] Number of roots=10, leaves=3, remote ranks=1
  [0] 4 <- (1,4)
  [0] 7 <- (1,5)
  [0] 9 <- (1,6)
  [1] Number of roots=10, leaves=0, remote ranks=0
```

**Comment by qing42102** [comment]
@cwsmith I didn't know that `sfPoint` only contains the boundary vertices for the leaves. It seems to have different vertex ownership than `vertexSF`. Isn't `sfPoint` telling us that rank 1 owns global vertices 0, 3, and 5?

I agree that we should ask more about SF and what is happening here.

**Comment by cwsmith** [comment]
Matt's response to our questions:
https://lists.mcs.anl.gov/pipermail/petsc-users/2020-August/041935.html

**Comment by qing42102** [comment]
@cwsmith For the added print statement in the comment [here](https://github.com/cwsmith/omegahPetsc/issues/4#issuecomment-673127297), do you have the output for 
```
fprintf(stderr, "%d 0.1 numVerticesAdj numVertices %d %d\n", rank, numVerticesAdj, numVertices);
``` 
and 
```
fprintf(stderr, "%d 0.2 numcells numVerticesAdj numVerticesGhost %d %d %d\n", rank, numCells, numVerticesAdj, numVerticesGhost);
```
Thanks in advance.

**Comment by cwsmith** [comment]
@qing42102 The complete output is attached.
[log.txt.gz](https://github.com/cwsmith/omegahPetsc/files/5074669/log.txt.gz)

**Comment by qing42102** [comment]
@cwsmith I currently hit a problem with the creation of SF. From Matt's email, the leaves contain the ghost vertices and point back to the owners. In the `pointSF` output from before, point 4, 5, 6 on rank 1 (which represents vertices 0, 3, 5) are ghost vertices and points back to the owner, 4, 7, 9 on rank 0. 

However, with the Omega_h ownership array, I only know if a vertex is a ghost when checking on the non-owner process. So instead it is reversed. Rank 0 contains the ghost vertices and point back to the non-owners. This is the output I currently get. 
```
PetscSF Object: 2 MPI processes
  type: basic
    sort=rank-order
  [0] Number of roots=10, leaves=0, remote ranks=0
  [1] Number of roots=10, leaves=3, remote ranks=1
  [1] 4 <- (0,4)
  [1] 5 <- (0,7)
  [1] 6 <- (0,9)
```

I am thinking of a solution with other DMPlex functions, but if you have any ideas using Omega_h, please let me know.

**Comment by cwsmith** [comment]
@qing42102 I think the issue is knowing if (a) the entity is on an inter-process boundary (a 'part boundary') and if so (b) who is the owner.

We have the code for (b) already by using the `ask_owners.ranks` array to get the `Remotes` rank info.  For the record, it contains an integer indicating which rank owns the given vertex. In Omega_h, if rank `p` is the owner of a vertex then the `ask_owners.ranks` entry corresponding to it will contain `p` *on all processes*; all 'ghosts', non owners, point back to the owning rank.  

To determine the answer to (a), call `mark_exposed_sides`:
https://github.com/SNLComputation/omega_h/blob/2e339ed435e113f6ded1f4621b520ceb03e306b0/src/Omega_h_mark.hpp#L24
Here is an example of its use for a 2d mesh (which will be the use case in xgcm):
https://github.com/SCOREC/pumi-pic/blob/295337486ece960592546ab17b5022a57e88db7c/src/pumipic_adjacency.hpp#L528
The term 'side' refers to mesh faces in a 3d mesh and edges in a 2d mesh.  After marking which edges are on the boundary you'll want to transfer the 'marks' to the vertices.  The following should work:

- get the array of vertices bounding each edge (edge-to-vertex downward adjacency)
- create an array, `exposed_verts`, to hold one integer per vertex
- loop over the edges and their downward vertices and set exposed_verts to `1` for both vertices if the edge is 'marked'

**Comment by cwsmith** [comment]
The master branch (138059573f38de6b833d85f7e121eac24a404e10) has a working call to `DMPlexCreateFromCellListParallelPetsc` (tested with square and xgc meshes on 2 and 4 processes).  The trick was distributing the vertex coordinates by global id into contiguous blocks on each process via MPI send/recv.  


24k_xgc_p4_ranks
<img src="https://user-images.githubusercontent.com/1024438/90931760-4db81f80-e3cb-11ea-991f-aa41254a8843.png" width="400">
24k_xgc_p4
<img src="https://user-images.githubusercontent.com/1024438/90931762-4ee94c80-e3cb-11ea-83b8-0af0425b2bae.png" width="400">
24k_xgc_p2
<img src="https://user-images.githubusercontent.com/1024438/90931766-501a7980-e3cb-11ea-9c25-4e49e4336946.png" width="400">

If we want to frequently adapt and convert the mesh we should pursue using the omegah dist to share element counts with neighboring processes (share one or more mesh vertices) needed to build the pointSF.  That change is here:
https://github.com/cwsmith/omegahPetsc/blob/499ca762329b783e597ec5330f9fec625810860a/ex12.cpp#L626
and the branch testing dist usage is here:
https://github.com/cwsmith/omegahPetsc/tree/distExchElmCnt
